snowflake:
  account: ${SNOWFLAKE_ACCOUNT}
  user: ${SNOWFLAKE_USER}
  password: ${SNOWFLAKE_PASSWORD}
  database: ${SNOWFLAKE_DB}
  warehouse: ${SNOWFLAKE_WH}
  role: ${SNOWFLAKE_ROLE}
  schema: ${SNOWFLAKE_SCHEMA}
  yield_prediction_data_query: "SELECT * FROM AGROSENSE_DB.AGROSENSE_SCH.FCT_ML_TRAINING_DATASET"

mlflow:
#  tracking_uri: "http://localhost:5001"
  tracking_uri: "http://mlflow:5000"
  experiment_name: "crop_yield_prediction"
  registered_model_name: "CropYieldPredictor"

model:
  test_size: 0.2
  random_state: 42
  features_to_remove:
    - YIELD_EFFICIENCY
    - PESTICIDE_INTENSITY
  categorical_features:
    - AREA
    - CROP_TYPE
    - ERA

model_params:
  n_estimators: 100
  max_depth: 20
  min_samples_split: 5
  min_samples_leaf: 2
  random_state: 42
  n_jobs: -1

paths:
  models_dir: "ml_models/models"
  artifacts_dir: "ml_models/artifacts"
  logs_dir: "ml_models/logs"